### ISSUE TITLE
[BUG]  Cannot choose "Generate Token" for GCP asia-northeast1

### ISSUE THREAD

**Issue by walmsles** [momentohq/issues#1]
**Describe the bug**

Momento Docs clearly state  the regions of availability for GCP as: us-central1, us-east4, asia-northeast1.  [Docs link here](https://docs.momentohq.com/). 

When I am on the Generate Token console - I cannot choose asia-northeast1 as an option for API Token.

**To Reproduce**

1. Go to Web console
2. Click "Generate Token"
3. Choose GCP
4. Try and choose asia-northeast1

**Expected behavior**

To be able to choose **asia-northeast1**

**Desktop (please complete the following information):**

 - OS: Mac OS (M1)
 - Browser: Chrome
 - Version: 114.0.5735.106 (Official Build) (arm64)

**Comment by danielamiao** [comment]
@walmsles thank you for the report, we have made appropriate updates to ensure our docs and console are consistent. GCP asia-northeast1 is currently not available on Momento yet but we'll reach out as soon as it becomes available, thank you!
